FROM --platform=linux/amd64 mysql:8.0.33

ENV MYSQL_ROOT_PASSWORD=drupal_password_user_root
ENV MYSQL_DATABASE=drupal_database_name
ENV MYSQL_USER=drupal_database_user
ENV MYSQL_PASSWORD=drupal_database_password
      
EXPOSE 3306
