FROM mysql:8.0.33

ENV MYSQL_ROOT_PASSWORD=drupal_password_user_root
ENV MYSQL_DATABASE=drupal_staging
ENV MYSQL_USER=drupal_database_user_staging
ENV MYSQL_PASSWORD=drupal_database_password_staging
      
EXPOSE 3306
