FROM mysql:8.0.33

ENV MYSQL_ROOT_PASSWORD=drupal_password_user_root
ENV MYSQL_DATABASE=drupal_develop
ENV MYSQL_USER=drupal_database_user_develop
ENV MYSQL_PASSWORD=drupal_database_password_develop
      
EXPOSE 3306
