FROM mysql:8.0.33

ENV MYSQL_ROOT_PASSWORD=here_set_your_parameter
ENV MYSQL_DATABASE=here_set_your_parameter
ENV MYSQL_USER=here_set_your_parameter
ENV MYSQL_PASSWORD=here_set_your_parameter
      
EXPOSE 3306
